apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
  labels: 
    app: nginx-webserver
spec:
  containers:
  - name: nginx-webserver
    image: nginx:latest
    ports:
    - containerPort: 80

